import os
# Binance API configuration
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")


# BINANCE_API_KEY = "LbHBILQPXruQ1vnAXpvIiod3nmXYTlQZYTlnpLUQPkQFZ66mU0j5kwNI1mrgb6QL"
# BINANCE_API_SECRET = "v5lns9HLw5PNhNI4SqaBNcQkIVjjgzaTYadXNpMWy0wJtABoGZPPCOS2htx9uegG"
